// src/popup/TextInput.svelte
<script>
  import Input from '../common/Input.svelte';
  import LanguageSelect from './LanguageSelect.svelte';
  import { text, from } from '../stores/translation';

  let inputFocused = false;

  $: multiline = Math.floor($text.length / 25) > 0 || $text.includes('\n');
</script>

<div class="input-wrapper" class:multiline class:input-focused={inputFocused}>
  <Input
    autofocus
    on:focus={() => (inputFocused = true)}
    on:blur={() => (inputFocused = false)} />
  <div class="language-select">
    <LanguageSelect bind:value={$from} />
  </div>
</div>

<style>
  .input-wrapper {
    position: relative;
    border: 1px solid #cbd5e0;
    border-radius: 2px;
    display: flex;
    align-items: center;
    padding: 8px;
    transition: 0.12s ease-in-out;
  }

  .input-wrapper:hover {
    border-color: #718096;
  }

  /* focus-within is ugly due to possible focused select element */
  .input-wrapper.input-focused {
    border-color: #2d3748;
  }

  .language-select {
    align-self: flex-end;
    display: inline-block;
    margin: -4px -4px -4px 8px;
  }

  .multiline {
    flex-direction: column;
  }

  .multiline .language-select {
    margin-top: 4px;
  }
</style>

// packages/extension/src/popup/TextInput/index.tsx
import React, { useRef, useLayoutEffect } from 'react';
import autosize from 'autosize';
import { styled, Box, Flex } from '@fxtrot/ui';

import { useText } from '../store/utils';
import { FromLanguageSelect } from '../LanguageSelect';

export const TextInput: React.FC = () => {
  const inputRef = useRef<HTMLTextAreaElement>(null);
  const [text, setText] = useText();

  const multiline = Math.floor(text.length / 25) > 0 || text.includes('\n');

  useLayoutEffect(() => {
    const el = inputRef.current;

    if (el) {
      autosize(el);
      el.focus();
    }

    return () => {
      el && autosize.destroy(el);
    };
  }, [inputRef]);

  return (
    <Wrapper
      flow={multiline ? 'column' : 'row'}
      multiline={multiline}
      main="stretch"
      cross={multiline ? 'stretch' : 'center'}
    >
      <TextArea
        value={text}
        onChange={(e: any) => {
          setText(e.target.value);
        }}
        autoFocus
        ref={inputRef}
      />
      <SelectWrapper>
        <FromLanguageSelect />
      </SelectWrapper>
    </Wrapper>
  );
};

const TextArea = styled('textarea', {
  display: 'block',
  outline: 'none',
  border: 'none',
  resize: 'none',
  fontFamily: 'inherit',
  minHeight: '1rem',
  height: '1rem',
  maxHeight: '150px',
  width: 'calc(100% - 8px * 2)',
  boxSizing: 'content-box',
  overflow: 'hidden',
  fontSize: '$md',
  p: '$2',
  br: '$md',
  bc: 'transparent',
  color: '$text',
});

const SelectWrapper = styled(Box, {
  pr: '$1',
});

const Wrapper = styled(Flex, {
  'border': '1px solid $borderStill',
  'br': '$md',
  'transition': '0.12s ease-in-out',

  ':hover': { borderColor: '$borderHover' },

  '&:focus-within': {
    borderColor: '$borderActive',
  },

  'variants': {
    multiline: {
      true: {
        [`& > ${SelectWrapper}`]: {
          alignSelf: 'flex-end',
          pb: '$1',
        },
      },
    },
  },
});
