// src/common/TranslatorLink.svelte
<script>
  import { to, text } from '../stores/translation';
  import { getTranslatorLink } from '../utils';

  $: link = getTranslatorLink({ to: $to, text: $text });
</script>

<a href={link} target="_blank" rel="noopener">
  <slot />
</a>

<style>
  a {
    border-bottom: 1px solid #0072c9;
    color: #0072c9;
    outline: none;
    text-decoration: none;
    line-height: 0.9;
  }
  a:hover {
    border-bottom-color: #0060a9;
    color: #0060a9;
  }
</style>

// src/popup/TranslatorLink/TranslatorLink.tsx
import React from 'react';
import cx from 'classnames';

import styles from './styles.css';

import { useToLanguage, useText } from '../AppContext';
import { getTranslatorLink } from '../../utils';

const TranslatorLink: React.FC<React.DetailedHTMLProps<
  React.AnchorHTMLAttributes<HTMLAnchorElement>,
  HTMLAnchorElement
>> = ({ children, className, ...props }) => {
  const [to] = useToLanguage();
  const [text] = useText();

  return (
    <a
      href={getTranslatorLink({ to, text })}
      className={cx(styles.link, className)}
      target="_blank"
      rel="noopener"
      {...props}
    >
      {children}
    </a>
  );
};

export default TranslatorLink;
